### ISSUE TITLE
How to start playing snaps from some desired index inside a story? Can you suggest something.

### ISSUE THREAD

**Issue by Harshvk** [drawRect/Instagram_Stories#101]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by boominadhaprakash** [comment]
Hi @Harshvk 

We have already addressed this issue. Please refer #98 issue.

**Comment by boominadhaprakash** [comment]
@Harshvk Please reopen this issue if it is not solved yet.
