### ISSUE TITLE
Seems image and Video(If Portrait) not displaying full screen

### ISSUE THREAD

**Issue by ramanocs1145** [drawRect/Instagram_Stories#102]
**Describe the bug**
I can able to see full frame for IGStoryPreViewView and UICollectionView when I change constraint like below,

```
        NSLayoutConstraint.activate([
            self.leftAnchor.constraint(equalTo: snapsCollectionView.leftAnchor),
            self.topAnchor.constraint(equalTo: snapsCollectionView.topAnchor),
            snapsCollectionView.rightAnchor.constraint(equalTo: self.rightAnchor),
            snapsCollectionView.bottomAnchor.constraint(equalTo: self.bottomAnchor)])
```

But Seems In `IGStoryPreViewCell Y position having 39 instead of 0`

**To Reproduce**
Make build on iPhone 11 Pro Max simulator or device.

**Expected behavior**
Should have full screen based on `IGStoryPreViewView`

**Screenshots**
![HierarchyFullview](https://user-images.githubusercontent.com/25265355/84277816-9fce0080-ab51-11ea-9cce-122d9086a9c1.png)
![HierarchyForIGStoryPreViewCell](https://user-images.githubusercontent.com/25265355/84277830-a2305a80-ab51-11ea-9fe3-f707eb2f1ef4.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Xcode: 11.5
 - Device: iPhone 11 Pro Max 
 - iOS: 13.5
 - OS: 10.15.5

**Additional context**
FYI: I have tested your source on iOS 13.5, so I have added `cv.contentInsetAdjustmentBehavior = .never` on `IGStoryPreviewView collectionView`, cause automaticallyAdjustsScrollViewInsets is depreciated in iOS 11 `automaticallyAdjustsScrollViewInsets = false` 

In IGStoryPreviewController class I can't see any constraint related code for IGStoryPreviewView? 
How get it frame on there? 
AnimatedCollectionViewLayout manage and handle snapsCollectionView super view frame on IGStoryPreviewView class?

Kindly suggest me to make full screen and the above clarifications.

**Comment by ranmyfriend** [comment]
@ramanocs1145 We will check and update you :)

**Comment by ramanocs1145** [comment]
@ranmyfriend & @boominadhaprakash ,

It's fixed. I just return like `return CGSize(width: _view.snapsCollectionView.frame.width, height: _view.snapsCollectionView.frame.height)` even our required Deployment target from `iOS 11.0` on `sizeForItemAt from UICollectionViewDelegateFlowLayout` at `StoryPreViewViewController`

Thanks for giving this wonderful library for to support `Instagram Stories` for custom implementation.

**Comment by ranmyfriend** [comment]
You are great. Thanks for your support.
