### ISSUE TITLE
how to add this stories as a part of header in tableview?

### ISSUE THREAD

**Issue by pratikgajbhiye222** [drawRect/Instagram_Stories#105]
![Screenshot 2020-07-09 at 3 51 07 AM](https://user-images.githubusercontent.com/58308681/86976125-6cee4b00-c197-11ea-9773-d8869716ebb1.png)

I want to achieve this screen where this stories is the part of tableview header and also I want to add other collection view and list view at follow . Can you please help me with this?

**Comment by ranmyfriend** [comment]
Hi @pratikgajbhiye222 

Definitely you can use our library. So if you look at our IGHomeview -> We have used Basic CollectionView only. So you just create one Header View with our collection view how we have done in IGHomeView. And try to pass it to the UITableView header in Section or TableHeaderView. However you want?

Let us know if you face any issues.?

**Comment by pratikgajbhiye222** [comment]
Thanks , It helps me
