### ISSUE TITLE
RTL not supported

### ISSUE THREAD

**Issue by YazanQ** [drawRect/Instagram_Stories#118]
**Describe the bug**
when the app is in RTL stories video not working but sounds do and the controller will always open the first story

**Comment by YazanQ** [comment]
in case someone faced the same issue 
The scroll view in IGStoryPreviewCell should be forced from left to right
sv.semanticContentAttribute = .forceLeftToRight

**Comment by boominadhaprakash** [comment]
Thank you @YazanQ
