### ISSUE TITLE
cannot find 'IGAppUtility' in scope

### ISSUE THREAD

**Issue by fredsco** [drawRect/Instagram_Stories#122]
**Describe the bug**
When I add the "source" folder to my project and try to run I receive the following error: 'cannot find 'IGAppUtility' in scope'   in file: IGStoryPreviewController.swift (line: 117) this is also for 'IGStoryListCell' and  'IGAddStoryCell'

I have followed the step from the README.

Is it possible to give a quick demo on how I can successfully import the source code, and create in my own view controller a circle with a "story" to place wherever I want? 

Thank you in advance.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone project
2. Drag source folder to own project
3.  make it as group and save it

**Expected behaviour**
After importing the source folder any code in there should not give an error?

**Using the latest version of Xcode and iOS.

**Comment by fredsco** [comment]
UPDATE: I see that I also needed to import the "Module' folder and IGapputility 👍 

I'm still curious how i could init this in my viewcontroller

**Comment by boominadhaprakash** [comment]
Hi @fredsco 

We missed out to check this. Please give me sometime. I will fix this issue and update you.
