### ISSUE TITLE
There is issue with memory. it no releasing memory while we dismiss viewController

### ISSUE THREAD

**Issue by ghost** [drawRect/Instagram_Stories#123]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by boominadhaprakash** [comment]
Hi @Bhavik022 

Require some more details about the issue. It will be more helpful for us, if you provide any screen recorded video and elaborate your issues.

**Comment by ranmyfriend** [comment]
closing the ticket due to don't have proper details. Open this ticket whenever you want @Bhavik022
