### ISSUE TITLE
ipad issue

### ISSUE THREAD

**Issue by bogdanmatasaru** [drawRect/Instagram_Stories#136]
navigation between stories doesnt work on ipad

https://youtube.com/shorts/wVZZivVWCf0

thanks!

**Comment by boominadhaprakash** [comment]
@bogdanmatasaru We haven't wrote this code to support for iPad. We have created this repo to support for iPhone. We haven't even tested. for iPad. If possible you can look through the code and give us a pull request.

**Comment by pratikSttl** [comment]
not work in ipad, 1st story work when switch to 2nd story then not work.
