### ISSUE TITLE
How to save story id when every story start

### ISSUE THREAD

**Issue by poomwtd** [drawRect/Instagram_Stories#143]
I want to save story id to local storage to check seen and unseen story, so my question is which function do i have to put my code on. I already look on StoryPreviewProtocol but can't found function that trigger when every story start

Thanks for your help

**Comment by ranmyfriend** [comment]
Hi @goodboygb1 you can collect your viewed story using **snapIndex - didSet method** create your function in **StoryPreviewProtocol** and whenever the **SnapMovementDirectionState.Forward** direction called, you can throw your viewedSnap to your own viewcontroller. Story can have multiple snaps. snap mime type can be a image/Video/etc. How ever you can track which snap already viewed by which story. both you can capture with help of this!!!

**Comment by poomwtd** [comment]
Thanks a lot for your help :)
