### ISSUE TITLE
not work on ipad

### ISSUE THREAD

**Issue by pratikSttl** [drawRect/Instagram_Stories#144]
1st story work complete on ipad but in 2nd story progressbar not work on ipad.

**Comment by pratikSttl** [comment]
hello, plz give me solution.

**Comment by ranmyfriend** [comment]
Sorry for the late reply. Maybe the second story the URL get is deprecated. can you please check once @pratikSttl

**Comment by pratikSttl** [comment]
in iphone work properly but in ipad when directly select 2nd story then not work progressbar.
@ranmyfriend  if url get deprecated then not work in iphone also.

**Comment by ranmyfriend** [comment]
@pratikSttl We are not supporting to ipad and only it works very well on iphone. Sorry for that.

**Comment by ranmyfriend** [comment]
If you have any other issues. feel free to reopen the issue
