### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by ranmyfriend** [drawRect/Instagram_Stories#20]
- [x] Apply Codeable protocol and remove SwiftyJSON on our models i.e.. ___IGStories_,_IGStory_,IGSnap_,IGUser_ @boominadhaprakash 
- [x] Remove **SDWebImage** and create a helper for ImageFetcher, @note already NickLockWood written amazing wrapper for this. @refer https://github.com/nicklockwood/AsyncImageView @boominadhaprakash

**Comment by boominadhaprakash** [comment]
Hi Ranjith,

I have removed SDWebImage library and handled caching techniques using NSCache.
Can you please merge the code?

**Comment by ranmyfriend** [comment]
Nice!!!.

I have seen your branch **Boomi/SDWebImageRemoval**. And I have merged at **Master**. 

Now the Master branch is up to date.

Thanks.
Ranjith

**Comment by ranmyfriend** [comment]
Closing this task. Core functionalities are covered. Good job @boominadhaprakash 

Keep it up

Regards,
Ranjith
