### ISSUE TITLE
Video support

### ISSUE THREAD

**Issue by mrhaxic** [drawRect/Instagram_Stories#33]
Hello guys is there any chance to have video support also for the stories ?

**Comment by boominadhaprakash** [comment]
@mrhaxic Currently video support is not available. We will work on that and It will take some time(approx 1 week) to update that feature.

**Comment by mrhaxic** [comment]
Pleasure to hear that, Good luck

**Comment by boominadhaprakash** [comment]
Hi @mrhaxic 
Sorry for the much delay. Still we are working on that. Video support has been added but facing some issues while moving to next and previous snap. Once we done that, I will post the comment here.

**Comment by boominadhaprakash** [comment]
@mrhaxic 
If you want to test the Video support, you can find the source code under Boomi/VideoSupport branch.

**Comment by mrhaxic** [comment]
@boominadhaprakash Will test with my pleasure 👍

**Comment by boominadhaprakash** [comment]
@mrhaxic Sorry, I think I forgot to push the code. I will push it in 10 mins.

**Comment by janczakb** [comment]
@boominadhaprakash Have you added video support yet?

**Comment by chintanTBI** [comment]
Hello,
is video support functionality available?

Thanks

**Comment by ranmyfriend** [comment]
We need sometime to support this feature request. Please support on following the commits and branch updates on future.

Thanks,
Ranjith

**Comment by divyansh-iimjobs** [comment]
Hi @ranmyfriend, have you implemented the video support or still working on that?

**Comment by boominadhaprakash** [comment]
Hi @divyansh-iimjobs 
Greetings.

We have implemented Video functionality. But when we're tested out on the last couple of days back we found one issue.

**Here is the issue desc:**
Once the Video has been played, if we do the Left tap, the progress bar duration time is not taking video length duration. Instead, it is taking the default 5 seconds of duration. 

Note: Once end user gets an image it will display 5 seconds from the current time. Even the progress bar will show likewise. But in Video based on the duration the progress bar will show it.

The appropriate code is available on **"Boomi/VideoSupport"** branch, Can you please do a checkout from this branch and play with this. and feel free to raise any issues or feedback.

Thanks,
Boominadha Prakash

**Comment by boominadhaprakash** [comment]
Hi all @mrhaxic  @divyansh-iimjobs  @chintanTBI  @janczakb

We have implemented Video functionality. Please checkout the master branch and play with it.

Let us know if you face any issues and your feedbacks.

Regards,
Boominadha Prakash
