### ISSUE TITLE
move to next or previous picture tap gesture

### ISSUE THREAD

**Issue by danishnaeem57** [drawRect/Instagram_Stories#34]
Hi, first of all, thanks for this awesome library. Can you please tell us, how to implement "move to next or previous picture on tap gesture" just like instagram and whatsapp?

**Comment by boominadhaprakash** [comment]
Hi @danishnaeem57 
Thanks for submitting the issue. The logic behind that move to next and previous is, have to **add tap gesture to scrollView in IGStoryPreviewCell** and **manage the snapIndex based on the gestures direction**. 
You can try with this logic, Even we also started working on this feature with video functionality. Once we have completed this task from our end, we will intimate you. 

Thanks,
Boominadha Prakash

**Comment by danishnaeem57** [comment]
Hi.
Any update about previous picture tap gesture?

Thanks.

**Comment by ranmyfriend** [comment]
Sorry for being late about this fix. Actually, we have fixed it but facing some side effects on this. We were busy with something else. Give us some time.
Once we have fixed it let you know @danishnaeem57 

Keep in touch :)
Thanks,
Ranjith

**Comment by danishnaeem57** [comment]
Thanks for your reply @ranmyfriend 👍 Please do that ASAP. I am vigorously waiting for this library updates.

**Comment by chintanTBI** [comment]
Hello,
Any update regarding to the functionality of tap to go previous/next?
Thanks.

**Comment by danishnaeem57** [comment]
can you please tell us, how much time will it take for you guys to implement this feature? Thanks!

Regards.

**Comment by boominadhaprakash** [comment]
Hi @danishnaeem57 @chintanTBI 

Sorry for the delay. Still we are working on it. Will let you know the status by tomorrow.

**Comment by danishnaeem57** [comment]
ok @boominadhaprakash 
we will be waiting for your response.

Thanks.

**Comment by boominadhaprakash** [comment]
Hi @danishnaeem57 
We are working on it. Hope we will fix the bug by this Friday.

**Comment by danishnaeem57** [comment]
Thank you so much Sir. Take your time. I will check on it on Friday.

**Comment by boominadhaprakash** [comment]
@danishnaeem57 We have fixed left and right tap issues for pictures only. 
Check and don't hesitate to post your feedback as well as issues.

**Comment by danishnaeem57** [comment]
hi @boominadhaprakash , thank you so much that you have updated this and added required features. But still there are some problems with the features, you have added. Such as, if you open first story then tap right again and again till last story as quickly as you can, you can identify the problem e.g lagging, crash, damaged image progress bar at top, sometimes incomplete previous progress bar etc. Same goes to tap left. 

Another issue is, let say we have 4 stories and we open 3rd story and tap left right away, it should open up 2nd story. but it doesn't.

**Comment by danishnaeem57** [comment]
I have attached a zip containing screen recording which will give you better idea about bugs.


[bugs.zip](https://github.com/drawRect/Instagram_Stories/files/2747824/bugs.zip)

**Comment by ranmyfriend** [comment]
Thanks. We found ourself this bug yesterday but until otherwise user do fast taps on the picture then only this bug arises. So we are trying to fix this bug as soon as possible and let you know the update.

**Comment by danishnaeem57** [comment]
Awesome. Thank you so much guys! keep it up.

**Comment by boominadhaprakash** [comment]
Hi @danishnaeem57 

Greetings,
We have fixed that fast tap issues. Kindly go through the source code and play with that from **"master"** branch.
Spread the word.
Thanks for your patience. Let us know if you found any issues.

Regards,
Boominadha Prakash
