### ISSUE TITLE
Swift 4.2 - Instance member 'reuseIdentifier' cannot be used on type 'IGStoryPreviewCell'

### ISSUE THREAD

**Issue by janczakb** [drawRect/Instagram_Stories#35]

**Comment by boominadhaprakash** [comment]
@janczakb Sorry for the delayed response. We will check and let you know.

**Comment by boominadhaprakash** [comment]
@janczakb But we are currently using latest Xcode and Swift v4.2 only, we are getting this issue. Can you provide snap of code and screenshot? So that we can understand what you are trying to do and we can help you out.

Thanks,
Boominadha Prakash
