### ISSUE TITLE
Start with specific snap

### ISSUE THREAD

**Issue by pcentieiro** [drawRect/Instagram_Stories#50]
Hello!

Thanks for this library which I found it very robust and complete. While it supports to go to a specific story, how can I go to a specific snap before launching the story?

I tried to set lastPlayedSnapIndex before opening the story, but it gets confused and seems that all the progress bars start playing after that index.

Thanks!

**Comment by ranmyfriend** [comment]
Hi @pcentieiro 

Using **lastPlayedSnapIndex** its possible but we cannot go by blind index, Because if snapsCount is 2 but if you are setting lastplayedSnapIndex is 3 then the app may crash. It is improper. For example: if you setting the last playedSnapIndex = 3 and max snaps count is 5, then 0,1,2 snaps are already played. and also the progress bar for these snaps will get auto filled on the Preview screen. it will start on lastPlayedSnapIndex. If you still confuse. Please write your clear requirement here. we will help you.

Thanks,
Ranjith

**Comment by boominadhaprakash** [comment]
Hi @pcentieiro 

Give us sometime, we will test it and let you know.

**Comment by pcentieiro** [comment]
Thanks! I saw your edited posts. This is what I'm trying to achieve:

- Instead of having the "usual" 4 persons / 4 different stories (each one with n snaps), I have 4 Sports Highlights on a Collection View with horizontal scrolling.
- Each Sports Highlight only has 1 snap. So, think of it with 1 Highlight = 1 Snap.
- Since it would be weird to go to through all highlights like going through all stories (since one story only has one snap and I would have a progress bar per story filling the entire screen), I created 1 story with n snaps.
- But now, I need to click on 1 highlight at a specific position of the collection view and go directly to that highlight.

If I was not cleared enough, I can post a video if you want, but it is very similar to "Previews" in Netflix app :)

I was thinking in loading the story and then make "fake" clicks on the screen to go to the snap I want, but I wouldn't go forward without your feedback, because I don't know the impact on the rest of the code...

Tbh, I don't want to use another InstagramStories library, because from what I found, yours is the most complete in github. Is there anything where I can help?

PS: I don't have a problem with the previous snaps being filled (before lastPlayedSnapIndex). That's the intended behaviour really! The problem is the ones after it :)

**Comment by boominadhaprakash** [comment]
Hi @pcentieiro 

I have modified our Instagram Stories code to support your requirement.

Please download the check the code from this branch: **Boomi/lastplayedsnapissue**

Now you can blindly set snapIndex value in IGStoryPreviewController, WillDisplayCell method.

Sample code for you.

```
func collectionView(_ collectionView: UICollectionView, willDisplay cell: UICollectionViewCell, forItemAt  indexPath: IndexPath) {
        guard let cell = cell as? IGStoryPreviewCell else {
            return
        }
        //Taking Previous(Visible) cell to store previous story
        let visibleCells = collectionView.visibleCells.sortedArrayByPosition()
        let visibleCell = visibleCells.first as? IGStoryPreviewCell
        if let vCell = visibleCell {
            vCell.story?.isCompletelyVisible = false
            vCell.pauseSnapProgressors(with: (vCell.story?.lastPlayedSnapIndex)!)
            story_copy = vCell.story
        }
        
        //Prepare the setup for first time story launch
        if story_copy == nil {
            cell.willDisplayCellForZerothIndex(with: 2)
            return
        }
        if indexPath.item == nStoryIndex {
            let s = stories.stories[nStoryIndex+handPickedStoryIndex]
            cell.willDisplayCell(with: s.lastPlayedSnapIndex)
        }
    }
```
If you face any issues, please feel free to raise issues.

**Comment by pcentieiro** [comment]
Works flawlessly 👌

Thanks a lot man!!

**Comment by boominadhaprakash** [comment]
Welcome @pcentieiro

**Comment by sourish** [comment]
HI @boominadhaprakash / @pcentieiro , Could you please tell me how can i open a particular snap with snapIndex. Could you please brief me about this
