### ISSUE TITLE
Stories stuck when app goes to background and become active.

### ISSUE THREAD

**Issue by nvish-bikramsaini** [drawRect/Instagram_Stories#55]
Steps to reproduce:

View story -> make app go to background or switch to another app -> Come back to your app -> Story is blank and doesn't auto-start.

**Comment by boominadhaprakash** [comment]
Hi @nvish-bikramsaini 

We will check it and let you know once we fixed that issue

**Comment by boominadhaprakash** [comment]
Hi @nvish-bikramsaini 

Good day!!.

Thanks for posting that issue. We have fixed the issue what you have mentioned. Please pull the changes from master branch or download the source from master branch and check it.

If you still face any issues, let us know.
