### ISSUE TITLE
We cannot move to previous story by swiping left

### ISSUE THREAD

**Issue by deepak832** [drawRect/Instagram_Stories#57]
**Describe the bug**
When we start Story from 2nd Story or any story after 1st from top story list then we can't go to previous Story when do Swipe left

Swipe left story is only working when we go to next by Swipe right and come back by swiping left.

**To Reproduce**
1. Go to 'Top Stories'
2. Click on '2nd Story'
3. Scroll down to 'Swipe left to go to previous story'

**Expected behaviour**
It should allow to go to previous story in all condition without check that from which story we started timeline/stroy videos view.

**Comment by boominadhaprakash** [comment]
Hi @deepak832 
Thanks for raising the issue. Give us sometime.
We will work on it and let you know once we fixed that.

**Comment by boominadhaprakash** [comment]
Hi @deepak832 

We have fixed that issue. Please checkout this branch **issues/57** or download the source from this branch and check it out.

If you still face that issue, please let us know.

**Comment by deepak832** [comment]
Hi Boominandha,

Thanks for the quick fix, it's working fine. This is a great code in swift, looks very nice to me.

I am trying to add different player instead of AVPlayer, can you pleas assist where/what I should change so it work without much effort.

**Comment by boominadhaprakash** [comment]
Hi @deepak832 
Thanks for your nice words.
For player stuff, inside Source folder, you can find IGPlayerView.swift file. If you modify that code, you can implement your own player.

**Comment by deepak832** [comment]
Sure will try that.

Thanks for the help and quick fix.
