### ISSUE TITLE
Can you do the same in Java  for Android studio

### ISSUE THREAD

**Issue by anonym2** [drawRect/Instagram_Stories#61]
I searched everywhere and look like android programmer cant do a good job as you

**Comment by ranmyfriend** [comment]
Hi @anonym2 
Thanks for your kind words :)
Actually, we are happy to help if you are going to start the same thing in Android. We are basically iOS Developers but don't have much knowledge in Android Studio as well as Java. But if you are interested we can add you to our organization. What do you say?

If you know the Kotlin. and interested in replicating this repository in Android. We love to explore. Tell me about your interest in joining our Organisation. 

We don't know Kotlin but Syntax wise is the same as Swift. Now Ball is on your court!!!

Thanks,
Ranjith

**Comment by boominadhaprakash** [comment]
Hi @anonym2 

Please refer the below links. I am not sure whether the below repo code has complete functionality. But someone already created repo for Instagram Stories for Android Java.
1. [https://github.com/shts/StoriesProgressView](https://github.com/shts/StoriesProgressView)
2. [https://github.com/RahulJanagouda/StatusStories](https://github.com/RahulJanagouda/StatusStories)

**Comment by anonym2** [comment]
The links you gave me are bad qualities I have already tried them

**Comment by boominadhaprakash** [comment]
oh!!!
