### ISSUE TITLE
functionality to pause or play the current story

### ISSUE THREAD

**Issue by Arun30sep** [drawRect/Instagram_Stories#63]
I would like to request the feature to pause and play again from the point where it is paused in the stories section i.e. IGStoryPreviewController

Currently I'm not able to select pause the story when preforming specific actions like share. If it is already in the library. Please let me know what I can use.

**Comment by boominadhaprakash** [comment]
Hi @Arun30sep 

In IGStoryPreviewCell, you can find the longPressGesture code. You can use the same code for pause and play again. I think that code will be apt for your requirement.

```
@objc private func didLongPress(_ sender: UILongPressGestureRecognizer) {
        if sender.state == .began || sender.state == .ended {
            let v = getProgressView(with: snapIndex)
            let videoView = scrollview.subviews.filter{v in v.tag == snapIndex + snapViewTagIndicator}.first as? IGPlayerView
            if sender.state == .began {
                if videoView != nil {
                    v?.pause()
                    videoView?.pause()
                }else {
                    v?.pause()
                }
            }else {
                if videoView != nil {
                    v?.resume()
                    videoView?.play()
                }else {
                    v?.resume()
                }
            }
        }
    }
```
You can find the above same code in IGStoryPreviewCell. Please use the same for your requirement. Let us know, if it's not works properly or you struggle to add that code for your requirement.
