### ISSUE TITLE
iPad Rotation

### ISSUE THREAD

**Issue by pcentieiro** [drawRect/Instagram_Stories#64]
Hello!

I'm using the library for an Universal app with stories, and while on the iPhone I have the orientation locked to portrait, on iPad I support all orientations (since I want to support the multitasking iPad features). This means that it's necessary to support the stories both on landscape and portrait (the library already does this fine while loading the view controller, but it lacks proper rotations of the UI elements, if the device rotates).

Is this something that can be looked on?

Thanks!

**Comment by boominadhaprakash** [comment]
Hi @pcentieiro 

Actually, we have created and tested this library only on iPhone not in iPad. We will check your issues. Thanks for raising it.
It will help us more if you provide screenshots.

Regards,
Boominadha Prakash

**Comment by boominadhaprakash** [comment]
Hi @pcentieiro 

We got the issue and we are working on it. Give us some time. Let you know once we fixed that.

**Comment by pcentieiro** [comment]
Hi @boominadhaprakash !

Thanks for the help! Much appreciated. I've attached some screenshots with this issue.

Open on portrait: OK!
![Simulator Screen Shot - iPad Pro (11-inch) - 2019-05-15 at 11 21 28](https://user-images.githubusercontent.com/1585409/57768497-aa765600-7703-11e9-8cd0-8bf216717519.png)

Open on landscape: OK!
![Simulator Screen Shot - iPad Pro (11-inch) - 2019-05-15 at 11 20 41](https://user-images.githubusercontent.com/1585409/57768508-aea27380-7703-11e9-84a5-cc31b6e17029.png)

Rotating after opening on portrait on landscape:
![Simulator Screen Shot - iPad Pro (11-inch) - 2019-05-15 at 11 21 32](https://user-images.githubusercontent.com/1585409/57768521-b3ffbe00-7703-11e9-9e1e-ba63be799560.png)

:(

**Comment by boominadhaprakash** [comment]
@pcentieiro 

Thanks for sharing the screenshots. Will let you know, once we fixed. Thanks for your patience.

Regards,
Boominadha Prakash

**Comment by boominadhaprakash** [comment]
Hi @pcentieiro 

We hope that we have fixed the landscape orientation issues. Please checkout or download code from "issues/64" branch.

Let us know if its work fine or not. Side by side, we will also do the testing.

**Comment by pcentieiro** [comment]
Thanks man! 

Looking into it right now. Need to accomodate to the changes that I already did. 

Will come back in the next couple of hours.

**Comment by pcentieiro** [comment]
Hi @boominadhaprakash 

Just finished accommodate my logic into what you did, and whoa... it works so smoothly!!! Fantastic job!!!! 😲

I wish I could show you, but we can't release the app yet :) Once it is on the App Store, I'll show you.

This is by far the best support that I got from a iOS library! 🙌

**Comment by boominadhaprakash** [comment]
Hi @pcentieiro 
Glad to hear that it worked fine without any issues 👍 
Waiting to see your app in App Store. :)
