### ISSUE TITLE
Feature to add story with simple add text with different colors.

### ISSUE THREAD

**Issue by arpitjain03** [drawRect/Instagram_Stories#65]
Hi guys,

I am highly impressed by your work for story views exact similar to Instagram. 
I am looking for some workaround on creating add story feature.
Just want to know like if you guys are working on the same as in your demo you have mentioned as "Coming Soon".
If yes then when can I expect it on your repository?

Thanks in advance !!!

**Comment by ranmyfriend** [comment]
Hi @arpitjain03 

Sounds great :)

Sorry for the Confusion, Add Story and Story feed is up to your own implementation. we forgot to change **Coming Soon**

**Note:** Add Story functionality can differ based on the client Requirement.

Thanks
Ranjith
