### ISSUE TITLE
progress bar not works in iOS 11.0.1

### ISSUE THREAD

**Issue by coder4x** [drawRect/Instagram_Stories#70]
**Describe the bug**
progress bar not works in iOS 11.0.1

**To Reproduce**
run project in iOS simulator 11.0.1

**Expected behavior**
progress bar should start loading and increasing

**Desktop (please complete the following information):**
 - OS: iOS 11.0.1

**Comment by coder4x** [comment]
found it
just add this line to IGStoryPreviewHeaderView, line 229:

`                pv.topAnchor.constraint(equalTo: pvIndicator.topAnchor),
`

**Comment by boominadhaprakash** [comment]
@coder4x Thanks for created the issue and your solution works. I have modified the code as per your changes and the code is available in this branch "issues/70". Soon we will merge with master.
