### ISSUE TITLE
Images or videos not load in iOS 10

### ISSUE THREAD

**Issue by coder4x** [drawRect/Instagram_Stories#71]
**Describe the bug**
when i run in on a iOS 10 simulator it doesn't load or show the stories (images or videos)
maybe it's because of auto layout,

**To Reproduce**
run app in iOS 10

**Expected behavior**
it should work!

**Desktop
 - OS: iOS 10

**Comment by ranmyfriend** [comment]
@coder4x thanks for an opening issue. we will have look and let you know

**Comment by boominadhaprakash** [comment]
Hi @coder4x 

We have fixed the issue. Please checkout the code from the branch "issues/71".

Let us know, if you faced any issues.

**Comment by coder4x** [comment]
> Hi @coder4x
> 
> We have fixed the issue. Please checkout the code from the branch "issues/71".
> 
> Let us know, if you faced any issues.

I just tested it and now it works perfectly and loads images/videos
Thank you 🌹

**Comment by boominadhaprakash** [comment]
> > Hi @coder4x
> > We have fixed the issue. Please checkout the code from the branch "issues/71".
> > Let us know, if you faced any issues.
> 
> I just tested it and now it works perfectly and loads images/videos
> Thank you 🌹

Glad to hear :)
