### ISSUE TITLE
is this demo project available through storyboard ?

### ISSUE THREAD

**Issue by VenkateshAnnedi** [drawRect/Instagram_Stories#74]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by boominadhaprakash** [comment]
Can you please explain your requirements? So that we can guide you.

**Comment by boominadhaprakash** [comment]
Hi @VenkatReddyAnnadi,

We are awaiting for your reply.

Regards,
Boominadha Prakash

**Comment by boominadhaprakash** [comment]
Due to inactivity, I am closing this issue. Please reopen if you want in the future.

Thanks,
Boominadha Prakash
