### ISSUE TITLE
Any example here?

### ISSUE THREAD

**Issue by samma835** [drawRect/Instagram_Stories#77]
It's a really awesome project. But I don't know where to start after paste the sources to my project.

So is there an example to show how to start to code with this lib?

**Comment by samma835** [comment]
find some clues here.

[#37](https://github.com/drawRect/Instagram_Stories/issues/37)

**Comment by boominadhaprakash** [comment]
Hi @bullda 

Whatever code available in Github repository itself is example project. You can find the sample code under Modules folder.

If you find any difficulties to understand that, let us know. We will revamp the folder structure.

Regards,
Boominadha Prakash

**Comment by samma835** [comment]
Thank you! It works now. Nice job.
