### ISSUE TITLE
How can I fix " Use of undeclared type 'layoutType' "

### ISSUE THREAD

**Issue by federico2390** [drawRect/Instagram_Stories#80]
Inside the IGStoryPreviewView, after that I have paste the source folder, when I built the project, I receive this error: "Use of undeclared type 'layoutType" at line 14 .
How can I fix it?

**Comment by federico2390** [comment]
after that on top. Is there a guide about the use? after that I have paste the source folder, how can I call the file?

**Comment by ranmyfriend** [comment]
Hi @federico2390

The Layout type error you may get which is part of **AnimatedCollectionViewLayout** . Please copy the AnimatedCollectionViewLayout folder under **External** Folder in the Project Folder.

You no need to call anything extra, we have already handled this layout type on **IGStoryPreviewController.swift**

Please let me know if you want anything additional clarification?

**Comment by federico2390** [comment]
Ok but how can i show the collectionview of the stories inside one my view

Il giorno 20 dic 2019, alle ore 16:50, ranjit <notifications@github.com> ha scritto:

﻿

Hi @federico2390<https://github.com/federico2390>

The Layout type error you may get which is part of AnimatedCollectionViewLayout . Please copy the AnimatedCollectionViewLayout folder under External Folder in the Project Folder.

You no need to call anything extra, we have already handled this layout type on IGStoryPreviewController.swift

Please let me know if you want anything additional clarification?

**Comment by ranmyfriend** [comment]
Kindly refer **IGHomeController.swift** and **IGHomeView.swift**. In HomeViewController i have added collectionView like wise you also can do this on your view. Thats it!

**Comment by ranmyfriend** [comment]
Hi @federico2390 
Am closing it dude to the respective information I have already given, If anything helps required from us. Feel free to open this issue again
Happy Coding :)
