### ISSUE TITLE
Failed with error: Cannot Open

### ISSUE THREAD

**Issue by Franknxtn** [drawRect/Instagram_Stories#81]
I am receiving  Failed with error: Cannot Open error on while loading video. Images work as expected but video are throwing cannot open error.

**Comment by ranmyfriend** [comment]
@TheAdrenalineJunkie Sorry for that. Maybe the Video URL's expired I guess. we have to update the URL. Let me check and update you.

**Comment by ranmyfriend** [comment]
Hi @TheAdrenalineJunkie There was an issue regarding the video URLs and i replaced with **big_buck_bunny.mp4** Kindly take a pull from **master** branch. And let us know if you need anything else!
