### ISSUE TITLE
Ambiguous use of 'widthConstraint'

### ISSUE THREAD

**Issue by UtkuDalmaz** [drawRect/Instagram_Stories#84]
I am having Ambiguous use of 'widthConstraint' error

<img width="288" alt="Screen Shot 2020-02-24 at 15 48 01" src="https://user-images.githubusercontent.com/2130592/75154047-dd7f5880-571d-11ea-9d71-90bd1ad60de3.png">

**Comment by boominadhaprakash** [comment]
Hi @UtkuDalmaz 

We are appreciating you for raising this bug.

We have already closed this iOS 13 related bug.

**Please refer this link:** https://github.com/drawRect/Instagram_Stories/issues/82

If you are still facing this issue apart from that fix, let us know the exact scenario or environment specific. Let us know your Xcode version, Swift version and deployment target.

Regards,
Boominadha Prakash
