### ISSUE TITLE
Snap ImageView background color

### ISSUE THREAD

**Issue by UtkuDalmaz** [drawRect/Instagram_Stories#86]
I changed snap imageview's content mode from here

```
    private func createSnapView() -> UIImageView {
        let snapView = UIImageView()
        snapView.translatesAutoresizingMaskIntoConstraints = false
        snapView.tag = snapIndex + snapViewTagIndicator
        snapView.backgroundColor = .black
        snapView.contentMode = .scaleAspectFit
        scrollview.addSubview(snapView)
```
<img width="299" alt="Screen Shot 2020-03-05 at 13 23 01" src="https://user-images.githubusercontent.com/2130592/75972511-972bb580-5ee4-11ea-8c7d-4c0471c50003.png">

My problem is that When I use a photo that doesn't fit the screen, Aspect fit shows it with blank spaces.  Those space color is white, I want to change it to black. So I changed imageview's backgroundcolor but it didn't work. Do you have any idea?

**Comment by boominadhaprakash** [comment]
Hi @UtkuDalmaz 

Please check the below link, this issue has been already addressed. Let us know, if the below link not solved your problem.

https://github.com/drawRect/Instagram_Stories/issues/79#issuecomment-555847819

Regards,
Boominadha Prakash
