### ISSUE TITLE
A request to the server When snap viewed

### ISSUE THREAD

**Issue by UtkuDalmaz** [drawRect/Instagram_Stories#87]
I want to send a request to the server (seen request) when each snap viewed.

Where can I implement that request in the code? Can you help me?

**Comment by boominadhaprakash** [comment]
Hi @UtkuDalmaz 

You can implement server related code in **didCompleteProgress** method when snap moves automatically. Suppose user tap before snap progress completes, you can implement the server code in **didTapSnap/willMoveToPreviousOrNextSnap** method. You can find these methods in **IGStoryPreviewCell** class.

Regards,
Boominadha Prakash

**Comment by UtkuDalmaz** [comment]
@boominadhaprakash thank you.

**Comment by boominadhaprakash** [comment]
@UtkuDalmaz Welcome.
