### ISSUE TITLE
Questions & Advices 

### ISSUE THREAD

**Issue by ranmyfriend** [drawRect/Instagram_Stories#9]
- [x] We should not create UIImageView blindly for the Snaps_count. It should be on demand. Because user is going to check the snap one by one, and even we already showing him how many snaps is there under story with help of ProgressBars.
- [x] _CreateSnappers_ method should not have **High_Priority**. This is expensive code but it should not happen on Synchronous way. It should happen on Race condition. like it create snap and also app should do other work also.
- [x] How SDWebImage will be able to get to know UITableViewCell or UICollectionViewCell is getting reused. If its getting reused how come SDWebImageManager stops the Pending Request? If we get base idea on this we could be able to get to know -  **We should create Operation Queue or SDWebImage itself handle the Queue**
- [x]  Is there any better way to clear the Previous story running variables behalf of clearing it on _ScrollWillBegin_

**Comment by ranmyfriend** [comment]
We have covered all these issues and code improvisation has done.

**Comment by pushkardeshmukh1992** [comment]
Any reason for not using native progress bar?

**Comment by ranmyfriend** [comment]
Hi @pushkardeshmukh1992 
Actually first we tried using UIProgressBar only. But to control the progress bar is not easy and also faced a lot of challenges in Start, Resume, Stop, Reset operations.  That's why I referred someone on Github how we can achieve the UI progress bar functionality using UIView. Please have look at this specific repo for this functionality.
https://github.com/ranmyfriend/Instagram_ProgressBar

**Comment by pushkardeshmukh1992** [comment]
Hey @ranmyfriend 
I have built similar story playing feature by referring to this https://medium.com/@anitaa_1990/create-a-horizontal-paging-uiscrollview-with-uipagecontrol-swift-4-xcode-9-a3dddc845e92

If you check the implementation, Slides(UIViews) are created based on the number of stories!
So if there are 200 stories, then there are 200 UIViews created. And each Slide/Story will have 'x' posts.
So I am wondering if this a good approach for story feature?
I have observed few crashes when there are large number of Stories. And not sure about fixing those. Crash happens when there are 200+ stories and you keep moving story one by one somewhere around 100.
I think I will need to rewrite entire feature using CollectionViews to solve this problem. (Just like your approach!)
What's your opinion on this?

**Comment by ranmyfriend** [comment]
Hi @pushkardeshmukh1992 
Actually, the way you have written the Medium article which can be affordable for onboarding screen. It's good to have minimalistic screens with scroll view. But the best solution is to go with CollectionView. If you are going with Collection view, You will get Reusable benefit and handles by Apple. In our case, we are getting benefited by this reusable functionality which can give save us from Memory Hike and all.

In your case 200+ stories if you are going with UIScrollView, all of them on Memory. So it will crash. But we are going with UICollectionView we are not facing any issue. And for Persisting the Image assets, we have used NSCache or you can go with SDWebImage. It saves you a lot of unnecessarily loading the Image Assets.

I like your Article :) Keep writing

Thanks,
Ranjith

**Comment by pushkardeshmukh1992** [comment]
Sorry to disappoint you but that's not my article :)
I referred to that article when I wanted to build story playing feature like Instagram. But now with that approach, I am facing issues which I have mentioned earlier.

I really appreciate your replies :)

Thanks!

**Comment by ranmyfriend** [comment]
Cool :)

Take care

**Comment by pushkardeshmukh1992** [comment]
Hey @ranmyfriend, is there any way we can split the video buffers?
Like for example if there's total 60 seconds video loading from network.. I would want to load first 15 seconds and show loading indicator till 15 seconds are fetched. 
If we reach to 16th second, then it should request for next 15 seconds chunk..
This way we don't wait for entire video to be loaded and play!

How can this be achieved? Would be great if add some config in your video player :)

**Comment by ranmyfriend** [comment]
Hi @pushkardeshmukh1992 
I like your Question. Yeah, it is possible. We are also using **AVPlayer** Framework only. 
It is Achievable!!!
like showing indicator when the buffer is empty. Like Player is waiting for some data, then hide indicator, once it gets arrived. Will do this later. Now we already busy with some tasks. Let us complete it as soon as possible. then we will do this task too. and let you know once we completed.

Thanks for your Initiative 👍 

All the best
Ranjith

**Comment by pushkardeshmukh1992** [comment]
Good to know you are considering this :)
Could you point me to some article/doc/API from where this can be achieved?

**Comment by ranmyfriend** [comment]
@pushkardeshmukh1992 
I think you have to add this key in your observer on AVPlayer. 

```
avPlayer.addObserver(self, forKeyPath: "currentItem.playbackLikelyToKeepUp",
        options: .new, context: &playbackLikelyToKeepUpContext)
```

and this can give you this callback when a player is looking for data as well as once it gets arrived,

```
override func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey : Any]?, context: UnsafeMutableRawPointer?) {
    if context == &playbackLikelyToKeepUpContext {
        if avPlayer.currentItem!.isPlaybackLikelyToKeepUp {
           // loadingIndicatorView.stopAnimating() or something else
        } else {
           // loadingIndicatorView.startAnimating() or something else
        }
    }
}
```

I just pasted the above code from this link only. Please refer it here
(https://stackoverflow.com/questions/5401437/knowing-when-avplayer-object-is-ready-to-play)

and if you are still facing any issue then search for How to show/hide activity indicator when avplayer streaming data

Thanks,
Ranjith

**Comment by pushkardeshmukh1992** [comment]
I had seen this article :D . Wanted to know your approach :) 
Will play around this..
Thanks Ranjith!

**Comment by ranmyfriend** [comment]
Even I also use the same approach. Thanks for confirming 👍

Take care and Happy Coding
