### ISSUE TITLE
Video not getting resume when long Pressed

### ISSUE THREAD

**Issue by sourish** [drawRect/Instagram_Stories#91]
**Describe the bug**
When the video gets started playing and if i long press the video it pause's but when i leave it doesn't resume instead it skips to the next user story. could you kindly check this.

**To Reproduce**
1. Go to 'any user story which has video in it'
2. Click on 'Long Press on the Video to pause and leave it'

**Expected behavior**
The Video should be resumed to from where it has paused

**Screenshots**

**Desktop (please complete the following information):**
 - OS: swift 
 - Browser Simulator
 - Version iOS 13

**Smartphone (please complete the following information):**

**Additional context**

**Comment by boominadhaprakash** [comment]
Hi @sourish,

Thanks for raising the issue. Please capture the error and share it as video. So that it will be helpful for us to debug the issue. Because we are unable to reproduce this issue.

Regards,
Boominadha Prakash

**Comment by sourish** [comment]
[Screen Recording 2020-04-03 at 5.02.54 PM.mov.zip](https://github.com/drawRect/Instagram_Stories/files/4426948/Screen.Recording.2020-04-03.at.5.02.54.PM.mov.zip)
Thank you for the response @boominadhaprakash .
I have attached a zip containing the recorded video. Could you please check.

**Comment by ranmyfriend** [comment]
Hi @sourish 
I have checked your video. this is how the behaviour of **Instagram stories** till now dude. We have not implemented when it was paused and resuming.
Already have an issue regarding this.
https://github.com/drawRect/Instagram_Stories/issues/68

**Comment by sourish** [comment]
Hi @ranmyfriend ,

Thank you for the time. Ok dude.
