### ISSUE TITLE
Implementation of Text also to the user stories

### ISSUE THREAD

**Issue by sourish** [drawRect/Instagram_Stories#92]
**Is your feature request related to a problem? Please describe.**
Its a great framework you have created, respect for both of you bro. I would like to request to add text Story also to it.

**Describe the solution you'd like**
In the Preview of the Stories adding the text to it.

**Comment by ranmyfriend** [comment]
Hi @sourish 
This is already we mentioned in the **Toast** like go with your own implementation. 
If you have any doubts or something how you want to pitch it up for this specific let us know we can guide you.
