### ISSUE TITLE
Xcode vs Android Studio

### ISSUE THREAD

**Issue by BrandonAPZ** [drawRect/Instagram_Stories#99]
Hello everyone, I am an android developer, the work they have done for xcode is excellent but I would like to know if they have it also available for the android studio IDE

**Comment by ranmyfriend** [comment]
Hi @BrandonAPZ 
Greetings.
We are iOS developers and we made it only available for iOS platform. We don't know Android, in future we may do. But for now, we support only on iOS.
Sorry to say this.
